import argparse
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from edalize.edatool import get_edatool
import os.path
import struct
import sys
import shutil

FRAMEWORK_ROOT = Path(__file__).resolve().parent.parent
MILL_PATH = FRAMEWORK_ROOT / "mill"

@dataclass
class Target:
    name: str
    main_class: str
    chisel_args: list[str]
    verilog_defines: list[str]
    files: list[str]
    top_module: str
    part: str


# Generate Target list
TARGETS = []
for r in [1, 2, 3, 4]:
    TARGETS.append(
        Target(
            name=f"gamebub_rev{r}",
            main_class="platform.handheld.HandheldTop",
            chisel_args=[str(r)],
            verilog_defines=[f"BOARD_REV_{r}"],
            files=[
                f"verilog/handheld/rev_{r}.xdc",
                # Common
                "verilog/handheld/common.xdc",
                "verilog/handheld/top.sv",
                "verilog/handheld/pll_reset_generator.sv",
                "verilog/handheld/clk_wiz_hdmi.v",
                "verilog/picorv32.v",
                # HDMI
                "verilog/hdmi/src/audio_clock_regeneration_packet.sv",
                "verilog/hdmi/src/audio_info_frame.sv",
                "verilog/hdmi/src/audio_sample_packet.sv",
                "verilog/hdmi/src/auxiliary_video_information_info_frame.sv",
                "verilog/hdmi/src/hdmi.sv",
                "verilog/hdmi/src/packet_assembler.sv",
                "verilog/hdmi/src/packet_picker.sv",
                "verilog/hdmi/src/serializer.sv",
                "verilog/hdmi/src/source_product_description_info_frame.sv",
                "verilog/hdmi/src/tmds_channel.sv",
            ],
            top_module="top_handheld",
            part="xc7a100tcsg324-1",
        )
    )


FILE_TYPES = {
    ".xdc": "xdc",
    ".v": "verilogSource",
    ".sv": "systemVerilogSource",
    ".vhd": "vhdlSource",
    ".vhdl": "vhdlSource",
}

# Extra HDL sources needed by specific core classes, in addition to the
# Chisel output. Paths are relative to the fpga directory; directories are
# searched recursively. Order matters for VHDL (packages before users), so
# entries are listed explicitly where needed.
SNES_ROOT = "verilog/snes"
# PC Engine: the MiSTer TurboGrafx16 core (HuCard-only edit) vendored under
# verilog/pce (see verilog/pce/README.md and verilog/pce/tools/README-build.md).
PCE_ROOT = "verilog/pce"
CORE_FILES: dict[str, list[str]] = {
    "net.gamebub.core.snes.HandheldSnes": [
        # Generic memory / arithmetic wrappers
        f"{SNES_ROOT}/rtl/bram.vhd",
        f"{SNES_ROOT}/rtl/mlab.vhd",
        # Coprocessor ROM images (generated by tools/gen_roms.py)
        f"{SNES_ROOT}/rtl/generated/coprocessor_roms.vhd",
        # Packages first
        f"{SNES_ROOT}/rtl/65C816/P65816_pkg.vhd",
        f"{SNES_ROOT}/rtl/SPC700/SPC700_pkg.vhd",
        f"{SNES_ROOT}/rtl/PPU_PKG.vhd",
        f"{SNES_ROOT}/rtl/DSP_PKG.vhd",
        f"{SNES_ROOT}/rtl/chip/GSU/GSU_PKG.vhd",
        f"{SNES_ROOT}/rtl/chip/SPC7110/SPC7110_DEC_PKG.vhd",
        # Everything else
        f"{SNES_ROOT}/rtl/65C816",
        f"{SNES_ROOT}/rtl/SPC700",
        f"{SNES_ROOT}/rtl/chip",
        f"{SNES_ROOT}/rtl/CEGen.vhd",
        f"{SNES_ROOT}/rtl/SWRAM.vhd",
        f"{SNES_ROOT}/rtl/SMP.vhd",
        f"{SNES_ROOT}/rtl/PPU.vhd",
        f"{SNES_ROOT}/rtl/CPU.vhd",
        f"{SNES_ROOT}/rtl/DSP.vhd",
        f"{SNES_ROOT}/rtl/SNES.vhd",
        f"{SNES_ROOT}/rtl/cheatcodes.sv",
        # Save states (USE_SS=1). savestate_ui.sv is the MiSTer OSD front end
        # and is not used.
        f"{SNES_ROOT}/rtl/savestates.sv",
        f"{SNES_ROOT}/rtl/savestates_regs.sv",
        f"{SNES_ROOT}/rtl/savestates_map.sv",
        f"{SNES_ROOT}/rtl/savestates_sa1.sv",
        f"{SNES_ROOT}/rtl/main.v",
    ],
    # Listed in VHDL dependency order: every `entity work.X` / `use work.X`
    # reference is compiled after X. Not built on purpose: rtl/CEGen.vhd
    # (never instantiated), rtl/cache_2way.sv (MiSTer's DDR3-side cache; the
    # glue's LineBuffer/LineReadCache replace it) and rtl/dpram.vhd.altera
    # (the altsyncram original that rtl/xilinx/dpram.vhd replaces). The
    # per-core constraints verilog/handheld/core_pce.xdc are picked up by the
    # generic core_<name>.xdc rule in build() (--name pce), and the
    # Performance_Explore strategy set there applies to every core.
    "net.gamebub.core.pce.HandheldPce": [
        # Package first
        f"{PCE_ROOT}/rtl/HUC6280/HUC6280_PKG.vhd",
        # Xilinx-portable dual-port RAM (tdp_ram_bank + dpram, self-contained)
        f"{PCE_ROOT}/rtl/xilinx/dpram.vhd",
        # Initialised memories generated from the .mif files by
        # tools/gen_init_roms.py: pce_palette_ram (huc6260), pce_voltab_rom (psg)
        f"{PCE_ROOT}/rtl/generated/pce_init_roms.vhd",
        # HuC6280 CPU and PSG
        f"{PCE_ROOT}/rtl/HUC6280/AddSubBCD.vhd",
        f"{PCE_ROOT}/rtl/HUC6280/HUC6280_ALU.vhd",
        f"{PCE_ROOT}/rtl/HUC6280/HUC6280_AG.vhd",
        f"{PCE_ROOT}/rtl/HUC6280/HUC6280_MC.vhd",
        f"{PCE_ROOT}/rtl/HUC6280/HUC6280_CPU.vhd",
        f"{PCE_ROOT}/rtl/HUC6280/psg.vhd",
        f"{PCE_ROOT}/rtl/HUC6280/HUC6280.vhd",
        # VCE, VDC, VPC
        f"{PCE_ROOT}/rtl/huc6260.vhd",
        f"{PCE_ROOT}/rtl/huc6270.vhd",
        f"{PCE_ROOT}/rtl/huc6202.vhd",
        # Top level, bound from Chisel as the ExtModule `pce_top`
        f"{PCE_ROOT}/rtl/pce_top.vhd",
    ],
}


# The synthesis/timing probe top shares the PCE core files.
CORE_FILES["net.gamebub.core.pce.HandheldPceProbe"] = CORE_FILES["net.gamebub.core.pce.HandheldPce"]

# NES / Famicom: the MiSTer NES core subset vendored under verilog/nes (see
# verilog/nes/README.md). VHDL in dependency order (the save-state register
# package and entity first, then the T65 CPU); the SystemVerilog package
# regs_savestates.sv before every file that imports it; nes.sv (module NES,
# bound from Chisel as NesCore) last. The per-core constraints
# verilog/handheld/core_nes.xdc (= core_snes.xdc) come in through --name nes.
NES_ROOT = "verilog/nes"
CORE_FILES["net.gamebub.core.nes.HandheldNes"] = [
    f"{NES_ROOT}/rtl/bus_savestates.vhd",
    f"{NES_ROOT}/rtl/t65/T65_Pack.vhd",
    f"{NES_ROOT}/rtl/t65/T65_ALU.vhd",
    f"{NES_ROOT}/rtl/t65/T65_MCode.vhd",
    f"{NES_ROOT}/rtl/t65/T65.vhd",
    f"{NES_ROOT}/rtl/savestates.vhd",
    f"{NES_ROOT}/rtl/statemanager.vhd",
    f"{NES_ROOT}/rtl/regs_savestates.sv",
    f"{NES_ROOT}/rtl/apu.sv",
    f"{NES_ROOT}/rtl/ppu.sv",
    f"{NES_ROOT}/rtl/mappers/MMC1.sv",
    f"{NES_ROOT}/rtl/mappers/MMC2.sv",
    f"{NES_ROOT}/rtl/mappers/MMC3.sv",
    f"{NES_ROOT}/rtl/mappers/generic.sv",
    f"{NES_ROOT}/rtl/cart.sv",
    f"{NES_ROOT}/rtl/nes.sv",
]


# Neo Geo Pocket Color: the MiSTer NGPC core subset vendored under
# verilog/ngpc (see verilog/ngpc/README.md) and its Game Bub top level
# rtl/gamebub/ngpc_gamebub_core.sv (bound from Chisel as NgpcCore). The two
# t900 headers are `include`d by the decoder and sequencer: listed as include
# files, their directory becomes an include path. The per-core constraints
# verilog/handheld/core_ngpc.xdc come in through --name ngpc.
NGPC_ROOT = "verilog/ngpc/rtl"
CORE_FILES["net.gamebub.core.ngpc.HandheldNgpc"] = [
    f"{NGPC_ROOT}/t900/t900_defs.svh",
    f"{NGPC_ROOT}/t900/t900_decode_tables.svh",
    f"{NGPC_ROOT}/snd/z80/tv80/tv80_alu.v",
    f"{NGPC_ROOT}/snd/z80/tv80/tv80_core.v",
    f"{NGPC_ROOT}/snd/z80/tv80/tv80_mcode.v",
    f"{NGPC_ROOT}/snd/z80/tv80/tv80_reg.v",
    f"{NGPC_ROOT}/mem/cache_ram.v",
    f"{NGPC_ROOT}/mem/cache_ram_be.sv",
    f"{NGPC_ROOT}/t900",
    f"{NGPC_ROOT}/soc",
    f"{NGPC_ROOT}/video",
    f"{NGPC_ROOT}/snd/t6w28.sv",
    f"{NGPC_ROOT}/snd/ngp_mixer.sv",
    f"{NGPC_ROOT}/snd/z80/ngp_z80.sv",
    f"{NGPC_ROOT}/snd/ngp_snd.sv",
    f"{NGPC_ROOT}/cart",
    f"{NGPC_ROOT}/savestates",
    f"{NGPC_ROOT}/gamebub",
]

# Mega Drive / Genesis: the archived MiSTer Genesis core vendored under
# verilog/md (see verilog/md/README.md) and its Game Bub top level
# rtl/gamebub/md_gamebub_core.sv (bound from Chisel as MdCore). Mixed VHDL and
# (System)Verilog: the VHDL is listed in dependency order (the memories and the
# VDP's constants package before their users), the two FX68K ROM images are
# include files so their directory becomes an include path, and jt12_top.v and
# friends stay plain Verilog. The per-core constraints
# verilog/handheld/core_md.xdc come in through --name md.
MD_ROOT = "verilog/md/rtl"
CORE_FILES["net.gamebub.core.md.HandheldMd"] = [
    # VHDL, in dependency order
    f"{MD_ROOT}/xilinx/bram.vhd",
    f"{MD_ROOT}/vdp_common.vhd",
    f"{MD_ROOT}/vdp.vhd",
    f"{MD_ROOT}/T80/T80_Reg.vhd",
    f"{MD_ROOT}/T80/T80_ALU.vhd",
    f"{MD_ROOT}/T80/T80_MCode.vhd",
    f"{MD_ROOT}/T80/T80.vhd",
    f"{MD_ROOT}/T80/T80s.vhd",
    # The FX68K microcode and nanocode images (include-only)
    f"{MD_ROOT}/generated/fx68k_microrom.svh",
    f"{MD_ROOT}/generated/fx68k_nanorom.svh",
    # Plain Verilog
    f"{MD_ROOT}/jt12",
    f"{MD_ROOT}/jt89",
    f"{MD_ROOT}/fourway.v",
    f"{MD_ROOT}/audio_iir_filter.v",
    f"{MD_ROOT}/genesis_lpf.v",
    # SystemVerilog
    f"{MD_ROOT}/FX68K",
    f"{MD_ROOT}/gen_io.sv",
    f"{MD_ROOT}/teamplayer.sv",
    f"{MD_ROOT}/multitap.sv",
    f"{MD_ROOT}/system.sv",
    # The R58 save-state engine (a directory: ss_freeze_ctrl, ss_m68k_handler_test, ss_slot_engine,
    # ss_snapshot_orchestrator, ss_system_state)
    f"{MD_ROOT}/savestate",
    f"{MD_ROOT}/gamebub/md_gamebub_core.sv",
]


# Verilog defines per core class (Vivado project-wide). NGPC: as MiSTer's
# files.qip (SYNTHESIS, TV80_REFRESH, the K2GE dot-burst scanout), plus the
# cheat engine left out and the Game Bub LCD presenter.
CORE_DEFINES: dict[str, dict[str, object]] = {
    "net.gamebub.core.md.HandheldMd": {
        "MD_NO_CHEATS": 1,
        "MD_NO_SVP": 1,
        "MD_NO_PIER": 1,
    },
    "net.gamebub.core.ngpc.HandheldNgpc": {
        "SYNTHESIS": 1,
        "TV80_REFRESH": 1,
        "NGPC_DOT_BURST": 1,
        "NGPC_BURST_START": 60,
        "NGPC_NO_CHEATS": 1,
        "NGPC_GAMEBUB": 1,
    },
}


def collect_core_files(core_class: str) -> list[dict]:
    """Return edalize file entries for the extra sources of `core_class`."""
    if core_class == "net.gamebub.core.snes.HandheldSnes":
        # Regenerate the coprocessor ROM entities (zero-filled if no ROM dumps).
        subprocess.run([sys.executable, str(FRAMEWORK_ROOT / SNES_ROOT / "tools" / "gen_roms.py")], check=True)
    if core_class == "net.gamebub.core.md.HandheldMd":
        # Regenerate the FX68K microcode / nanocode includes from the vendored
        # .mem images. Deterministic output.
        subprocess.run([sys.executable, str(FRAMEWORK_ROOT / "verilog" / "md" / "tools" / "gen_fx68k_roms.py")], check=True)
    if core_class.startswith("net.gamebub.core.pce."):
        # Regenerate the initialised memories (VCE colour RAM, PSG volume
        # table) from the vendored .mif files. Deterministic output.
        subprocess.run([sys.executable, str(FRAMEWORK_ROOT / PCE_ROOT / "tools" / "gen_init_roms.py")], check=True)

    seen: set[Path] = set()
    files = []
    for entry in CORE_FILES.get(core_class, []):
        path = FRAMEWORK_ROOT / entry
        if path.is_dir():
            candidates = sorted(p for p in path.rglob("*") if p.suffix in FILE_TYPES or p.suffix == ".svh")
        else:
            candidates = [path]
        for candidate in candidates:
            if candidate in seen:
                continue
            if not candidate.exists():
                sys.exit(f"Missing core file: {candidate}")
            seen.add(candidate)
            if candidate.suffix == ".svh":
                # Include-only: edalize adds its directory to the include path.
                files.append(dict(name=candidate, file_type="systemVerilogSource", is_include_file=True))
                continue
            # Note: main.v must be compiled as plain Verilog: it connects VHDL
            # ports named `do`, which is a SystemVerilog keyword.
            files.append(dict(name=candidate, file_type=FILE_TYPES[candidate.suffix]))
    return files


def get_git_revision() -> str:
    try:
        revision = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True)
        revision = revision.strip()
    except:
        print("Failed to find Git revision")
        return ""

    return revision[:12]


def insert_bitstream_metadata(bitstream: bytearray, extra: str):
    # Very crude way of not parsing the Xilinx header
    # Assumes the first tag is "a" (design name)
    HEADER = b"\x00\x09\x0f\xf0\x0f\xf0\x0f\xf0\x0f\xf0\x00\x00\x01a"
    if bitstream[: len(HEADER)] != HEADER:
        raise SystemExit("Unexpected bitstream header")

    # Find the length of the tag
    index = len(HEADER)
    (length,) = struct.unpack(">H", bitstream[index : (index + 2)])
    if length < 1:
        return
    index += 2
    # Extract the tag
    tag = bitstream[index : (index + length)]
    # Modify the tag
    tag = tag[:-1] + extra.encode("utf-8") + bytearray([0])
    bitstream[index : (index + length)] = tag
    # Modify the length
    length = struct.pack(">H", len(tag))
    index = len(HEADER)
    bitstream[index : (index + 2)] = length


def build(
    name: str,
    target: Target,
    build_root: Path,
    core_class: str,
    project_root: Path,
    additional_file_dirs: list[Path] = [],
):
    files = []
    if build_root.exists():
        shutil.rmtree(build_root)
    build_root.mkdir(parents=True, exist_ok=True)

    # Run Chisel
    generate_root = build_root / "generated"
    args = [
        MILL_PATH,
        "-i",
        "--no-build-lock",
        "root.runMain",
        target.main_class,
        core_class,
        *target.chisel_args,
        f"--target-dir={generate_root}",
    ]

    result = subprocess.run(args, cwd=project_root)
    if result.returncode != 0:
        sys.exit("Chisel build failed")

    # Collect files from Chisel output
    filelist_path = generate_root / "filelist.f"
    with open(filelist_path) as f:
        for filename in f:
            path = filelist_path.parent / filename.rstrip()
            files.append(dict(name=path, file_type="systemVerilogSource"))

    # Add additional target RTL files
    additional_files = [FRAMEWORK_ROOT / f for f in target.files]
    for dir in additional_file_dirs:
        for (dir, _, dir_files) in os.walk(dir):
            dir = Path(dir)
            for file in dir_files:
                additional_files.append(dir / file)

    for file in additional_files:
        file_extension = file.suffix
        file_type = {
            ".xdc": "xdc",
            ".v": "verilogSource",
            ".sv": "systemVerilogSource",
            ".vhd": "vhdlSource",
            ".vhdl": "vhdlSource",
        }.get(file_extension)
        if not file_type:
            print("WARNING: Skipping unknown file type:", file)
        files.append(dict(name=file, file_type=file_type))

    # Add additional core-specific files (e.g. vendored HDL).
    for file in collect_core_files(core_class):
        files.append(file)

    # Per-core constraints (e.g. the SNES's SDRAM interface timing, which
    # depends on the core's SDRAM clock rate).
    core_xdc = FRAMEWORK_ROOT / "verilog" / "handheld" / f"core_{name}.xdc"
    if core_xdc.exists():
        files.append(dict(name=core_xdc, file_type="xdc"))

    # Make all file paths relative to build root.
    for f in files:
        f["name"] = os.path.relpath(str(f["name"]), str(build_root))

    # Set Verilog defines
    parameters = {
        name: {"datatype": "bool", "paramtype": "vlogdefine", "default": True}
        for name in target.verilog_defines
    }
    for define, value in CORE_DEFINES.get(core_class, {}).items():
        parameters[define] = {"datatype": "int", "paramtype": "vlogdefine", "default": value}

    # Run Vivado (via Edalize)
    edam = {
        "name": name,
        "toplevel": target.top_module,
        "files": files,
        "parameters": parameters,
        "tool_options": {"vivado": {"part": target.part}},
    }
    backend = get_edatool("vivado")(edam=edam, work_root=build_root)
    backend.configure()

    # Implementation effort. The SNES core fills the device (~70% LUTs) and
    # its longest paths run from the S-CPU / SA-1 through the memory glue
    # into the SRAM controller's output registers; the default strategy
    # leaves them a fraction of a nanosecond short. Edalize has no option
    # for this, so the setting is prepended to the run script it generates
    # (sourced on every build, before implementation starts).
    # The NGPC core also needs the post-route physical optimisation: with the
    # TLCS-900/H multicycle families in place its routed design lands a tenth
    # of a nanosecond short on the decode-hold to bus-hold paths, and that step
    # closes them (the strategy is Performance_Explore plus post-route phys_opt).
    strategy = ("Performance_ExplorePostRoutePhysOpt"
                if core_class.endswith("HandheldNgpc") else "Performance_Explore")
    run_tcl = build_root / f"{name}_run.tcl"
    run_tcl.write_text(
        "# Added by build_core.py: implementation effort for timing closure.\n"
        f"set_property strategy {strategy} [get_runs impl_1]\n"
        "\n" + run_tcl.read_text()
    )

    backend.build()

    # After a successful build, the bitstream will be at <name>.bit.
    bitstream_path = build_root / f"{name}.bit"
    if not bitstream_path.exists():
        sys.exit("Bitstream path doesn't exist")
    print("Found bitstream at", bitstream_path)
    bitstream = bytearray(open(bitstream_path, "rb").read())

    # Determine Git Revision
    git_revision = get_git_revision()
    if git_revision:
        print("Git revision:", git_revision)

    # Insert Git information into bitstream
    insert_bitstream_metadata(bitstream, ";GitRev=" + git_revision)
    open(bitstream_path, "wb").write(bitstream)

    # Compress bitstream (heatshrink)
    try:
        import heatshrink2
        compressed_path = bitstream_path.with_name(bitstream_path.name + ".hs")
        compressed = heatshrink2.encode(bitstream, window_sz2=9, lookahead_sz2=6)
        with open(compressed_path, "wb") as f:
            f.write(compressed)
    except ImportError:
        # Skip heatshrink
        pass

    print("*" * 80)
    print("Bitstream:")
    print(bitstream_path.resolve())
    print("*" * 80)


def main(args) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--name", required=True)
    parser.add_argument(
        "--target",
        choices=[t.name for t in TARGETS],
        required=True,
        help="Target hardware",
    )
    parser.add_argument("--build-root", required=True, type=Path)
    parser.add_argument("--project-root", type=Path)
    parser.add_argument("--core-class", required=True)
    parser.add_argument("--additional-file-dirs", nargs="*", default=[], type=Path)

    args = parser.parse_args(args)
    target = next(t for t in TARGETS if t.name == args.target)
    build(
        args.name,
        target,
        args.build_root.resolve(),
        args.core_class,
        args.project_root or FRAMEWORK_ROOT,
        args.additional_file_dirs,
    )


if __name__ == "__main__":
    main(sys.argv[1:])
