#!/bin/sh
# Simulate HandheldMd (as generated by a mill elaboration or a build) with
# tb_system.sv in xsim: the glue, the vendored machine, the real SDRAM
# controller with a chip model, the host protocol as the firmware drives it.
# Usage: [STATES=<.ss file>] run_system.sh <rom file> <workdir> [xsim plusargs, no '=' ...]
#   e.g. run_system.sh "Comix Zone (USA).md" /tmp/md-sys +frames60 +dump_from50 +dump_every5
# GEN = the directory with the generated SystemVerilog (default build/md-elab).
# Needs Vivado's bin directory on PATH. REBUILD=1 recompiles.
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
RTL="${MD_RTL:-$HERE/../../rtl}"
GEN="${GEN:-$HERE/../../../../../build/md-elab}"
ROM="$1"; WORK="$2"; shift 2
mkdir -p "$WORK"
python "$HERE/../../tools/gen_fx68k_roms.py" > /dev/null
python "$HERE/../make_hex.py" "$ROM" "$WORK"
# STATES=<.ss file>: preload the States file (host words like the cartridge, see make_hex.py)
# so a load can put the machine into a saved scene; adds +preload1 +pwords<n>. Pick the slot
# with +slot<n> (0 = slot 1).
PRELOAD_ARGS=""
if [ -n "$STATES" ] && [ -f "$STATES" ]; then
  python - "$STATES" "$WORK" <<'PY'
import pathlib, sys
data = bytearray(pathlib.Path(sys.argv[1]).read_bytes())
if len(data) % 4: data += b"\xFF" * (4 - len(data) % 4)
words = [int.from_bytes(data[i:i + 4], "little") for i in range(0, len(data), 4)]
pathlib.Path(sys.argv[2], "states_words.hex").write_text("\n".join(f"{w:08x}" for w in words) + "\n")
PY
  PRELOAD_ARGS="+preload1 +pwords$(( ( $(stat -c %s "$STATES") + 3 ) / 4 ))"
fi
cd "$WORK"
# EXTRA_DEFS: more -d defines, e.g. "-d MD_SIM_SHORT_WATCHDOG" (the engine's 2.5 s watchdog at 0.31 s).
DEFS="-d MD_NO_CHEATS -d MD_NO_SVP -d MD_NO_PIER ${EXTRA_DEFS}"
if [ ! -f xsim.dir/tb_system_snap/xsimk.exe ] || [ -n "$REBUILD" ]; then
  GENFILES=""
  for f in MMCM PLL PipelineMemoryArbiter PipelineInterfaceBridge PipelineMemoryLowPriorityMux \
           MdRomStore MdSaveRamWindow MdSaveStatePort MdSaveSlotScanner \
           MdVideoCapture AudioDecimator ram_256x32 Queue256_Sample AudioRateAdapter \
           BurstSdramController HandheldMd; do
    GENFILES="$GENFILES $GEN/$f.sv"
  done
  xvhdl --relax "$RTL/xilinx/bram.vhd" "$RTL/vdp_common.vhd" "$RTL/vdp.vhd" \
        "$RTL/T80/T80_Reg.vhd" "$RTL/T80/T80_ALU.vhd" "$RTL/T80/T80_MCode.vhd" \
        "$RTL/T80/T80.vhd" "$RTL/T80/T80s.vhd" > xvhdl.log
  xvlog --relax "$RTL"/jt12/*.v "$RTL"/jt12/mixer/*.v "$RTL"/jt12/adpcm/*.v \
        "$RTL"/jt89/*.v "$RTL"/fourway.v "$RTL"/audio_iir_filter.v "$RTL"/genesis_lpf.v \
        "$HERE/sim_primitives.v" > xvlog_v.log
  xvlog --relax -sv $DEFS -i "$RTL/generated" "$HERE/sim_defines.v" \
        "$RTL"/system.sv "$RTL"/gen_io.sv "$RTL"/multitap.sv "$RTL"/teamplayer.sv \
        "$RTL"/FX68K/*.sv "$RTL"/savestate/*.sv "$RTL"/gamebub/*.sv $GENFILES \
        "$HERE/sdram_model.sv" "$HERE/tb_system.sv" > xvlog_sv.log
  xelab --relax -debug off -O3 tb_system -s tb_system_snap > xelab.log
fi
ARGS=$(cat cart.args)
xsim tb_system_snap -R $(for a in $ARGS $PRELOAD_ARGS "$@"; do printf -- '--testplusarg %s ' "${a#+}"; done) > xsim.log 2>&1 || true
tail -8 xsim.log
