#!/usr/bin/env python3
"""Turn the FX68K microcode and nanocode images into SystemVerilog includes.

Upstream `rtl/FX68K/fx68k.sv` loads them with

    initial begin $readmemb("microrom.mem", uRam); end

which depends on the tool's search path for a bare relative filename, and
Vivado and xsim resolve that differently (and differently again from
Quartus). This writes the same contents as explicit element assignments in
`rtl/generated/`, which both tools read identically and from which Vivado
infers a block RAM ROM exactly as it does from `$readmemb`.

Deterministic: the output depends only on the vendored `.mem` files.
Run from anywhere; paths are relative to this file.
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "rtl" / "FX68K"
OUT = ROOT / "rtl" / "generated"

ROMS = [
    # (source, output, array name, bit width, depth)
    ("microrom.mem", "fx68k_microrom.svh", "uRam", 17, 1024),
    ("nanorom.mem", "fx68k_nanorom.svh", "nRam", 68, 336),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for source, output, array, width, depth in ROMS:
        lines = [
            line.strip()
            for line in (SRC / source).read_text().splitlines()
            if line.strip()
        ]
        if len(lines) != depth:
            raise SystemExit(f"{source}: expected {depth} lines, found {len(lines)}")
        for line in lines:
            if len(line) != width or set(line) - set("01"):
                raise SystemExit(f"{source}: not {width} binary digits: {line!r}")
        body = "\n".join(
            f"    {array}[{i}] = {width}'b{value};" for i, value in enumerate(lines)
        )
        (OUT / output).write_text(
            f"// Generated by tools/gen_fx68k_roms.py from rtl/FX68K/{source}.\n"
            f"// Do not edit. Part of the vendored FX68K (see ../../README.md).\n"
            "initial begin\n"
            f"{body}\n"
            "end\n",
            newline="\n",
        )
        print(f"{output}: {depth} x {width} bits")


if __name__ == "__main__":
    main()
